# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ">catthoughts"
email: louis.tur@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  What would a cat, if placed infront of computer screen rather than window, think about
  when coding?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://spacedrabbit.github.io" # the base hostname & protocol for your site
twitter_username: louistur
github_username:  spacedrabbit

# Build settings
markdown: kramdown
